### ISSUE TITLE
undefined index $response->country

### ISSUE THREAD

**Issue by jfilla** [markus-perl/gender-api-client#1]
hi,
calling
`$this->genderApiClient->getByMultipleNames(['name1', 'name2'])`
leads to
`undefined index $response->country` in [MultipleNames:90](https://github.com/markus-perl/gender-api-client/blob/master/src/GenderApi/Client/Result/MultipleNames.php#L90)

**Comment by jfilla** [comment]
[pull request ](https://github.com/markus-perl/gender-api-client/pull/2)

**Comment by markus-perl** [comment]
Hi jfilla, 
Thank you for taking the time and reporting this bug to me.
Pull request -> merged.

Thanks, Markus
